config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: 'categories#index', as: :authenticated_root
  end
  root to: 'splash#index'

  devise_for :users
  
  resources :activities

  resources :categories
  get 'welcome', to: 'splash#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, Activity, author: user
    can :manage, Category, user: user
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  validates :name, :amount, :categories, presence: true
  validates :amount, numericality: { greater_than: 0 }

  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  validates :icon, presence: true, length: { maximum: 2 }

  belongs_to :user
  has_and_belongs_to_many :activities

  def total_amount
    activities.sum(:amount)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :email, presence: true
  has_many :activities
  has_many :categories
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  load_and_authorize_resource

  # GET /activities or /activities.json
  def index
    redirect_to categories_path
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # POST /activities or /activities.json
  def create
    @activity = Activity.new(activity_params)
    @activity.author = current_user

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity.categories.first, notice: 'Transaction was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def activity_params
    params.require(:activity).permit(:name, :amount, category_ids: [])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
  before_action :set_category, only: %i[show]

  # GET /categories or /categories.json
  def index
    @categories = current_user.categories
  end

  # GET /categories/1 or /categories/1.json
  def show
    @activities = @category.activities.order(created_at: 'desc')
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # POST /categories or /categories.json
  def create
    @category = current_user.categories.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to root_path, notice: 'Category was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.includes(:activities).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index; end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/activities/_form.html.erb
<div class='default-font'>
  <%= form_with(model: activity) do |form| %>
    <div class='login-header is-flex is-justify-content-space-between is-align-items-center p-2 mb-2'>
      <%= link_to 'BACK', activities_path, class: "has-text-white is-size-7"  %>
      <div>
        <p class="has-text-white is-size-5">NEW TRANSACTION</p>
      </div>
      <%= form.submit "SAVE", class:'form-submit has-text-white is-size-7'%>
    </div>
    <%= render "devise/shared/error_messages", resource: activity %>
    <div class='pt-2'>
      <%= form.text_field :name, autofocus: true, placeholder: "Name", class: "input", required: true %>
      <%= form.number_field :amount, placeholder: "Amount", class: "input", required: true %>
      <%= form.collection_select :category_ids, current_user.categories.order(:name), :id, :name, {}, { class: "input", multiple: true } %>
    </div>
  <% end %>
</div>

app/views/activities/_index.html.erb
<div class='default-font'>
	<div class='m-2 p-4 card is-flex is-justify-content-space-between'>
		<div>
			<h5 class='mb-2 has-text-grey'><%= activity.name %></h5>
			<small><%= activity.created_at.strftime("%d %b %Y") %></small>
		</div>
		<h6 class='has-text-weight-semibold'>$<%= activity.amount %></h6>
	</div>
</div>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/new.html.erb
<%= render 'form', activity: @activity %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @activity.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @activity.amount %>
</p>

<p>
  <strong>User:</strong>
  <%= @activity.user_id %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/categories/_category.html.erb
<div class='default-font'>
  <%= link_to category_url(category) do %>
    <li >
      <div class='m-3 p-4 card is-flex is-justify-content-space-between'>
        <div class='image'>
          <%= category.icon %>
        </div>
        <div>
          <h5><%= category.name.capitalize %>
          <br>
          <small><%= category.created_at.strftime('%-d %h %Y')%></small>
        </div>
        <small class='has-text-weight-semibold'>$<%= category.total_amount %></small>
      </div>
    </li>
  <%  end %>
</div>

app/views/categories/_form.html.erb
<div class='default-font'>
  <%= form_with(model: category) do |form| %>
    <div class='login-header is-flex is-justify-content-space-between is-align-items-center p-2 mb-2'>
      <%= link_to 'BACK', categories_path, class: "has-text-white is-size-7" %>
      <div>
        <p class="has-text-white is-size-5">NEW CATEGORY</p>
      </div>
      <%= form.submit "SAVE", class:'form-submit has-text-white is-size-7'%>
    </div>
    <%= render "devise/shared/error_messages", resource: category %>
    <div>
      <%= form.text_field :name, autocomplete: "name", placeholder: "Name", class: "input", required: true %>
      <%= form.text_field :icon, autocomplete: "icon", placeholder: "Icon", class: "input", required: true %>
    </div>
  <% end %>
</div>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class='default-font'>
  <header class='login-header is-flex is-justify-content-space-between is-align-items-center p-2 mb-2'>
    <span></span>
    <span class="has-text-white is-size-4">CATEGORIES</span>
    <%= link_to "Log out", destroy_user_session_path, class:'form-submit has-text-white is-size-7', method: :delete %>
  </header>
  <ul>
    <% if @categories.empty? %>
      <div>
        No categories for now
      </div>
    <% else %>
      <% @categories.each do |category| %>
        <%= render partial: 'category', locals: { category: category } %> 
      <% end %>
    <% end %>
  </ul>

  <footer class='page-footer'>
    <%= link_to 'ADD A NEW CATEGORY', new_category_path, class: 'buttons has-text-white has-text-weight-medium' %>
  </footer>
</div>

app/views/categories/new.html.erb
<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<div class='default-font'>
  <header class='login-header is-flex is-justify-content-space-between is-align-items-center p-2 mb-2'>
	  <%= link_to 'Back', categories_path, class:'form-submit has-text-white is-size-6' %>
    <h1 class="has-text-white is-size-4">TRANSACTIONS</h1>
    <span></span>
  </header>
  <div>
    <div class='is-flex is-justify-content-space-between pt-3 px-3'>
      <p>Gift Credit:</p>
      <p class='has-text-weight-semibold'>$<%= @category.total_amount %></p>
    </div>
    <hr>
  </div>
  
  <ul>
  <% if @activities.empty? %>
    <div class='has-text-centered'>
      No Transactions for now
    </div>
  <% else %>
    <% @activities.each do |activity| %>
      <%= render partial: 'activities/index', locals: { activity: activity } %>
    <% end %>
  <% end %>
  </ul>
</div>
<footer class='page-footer default-font'>
  <%= link_to 'ADD A NEW TRANSACTION', new_activity_path, class: 'buttons has-text-white has-text-weight-medium' %>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/splash/index.html.erb
<div class='splash-body default-font'>
  <h1 class='splash-title'>Snapscan</h1>

  <div class='splash-links'>
    <%= link_to 'LOGIN', new_user_session_path, class: "button is-info is-active mb-2" %>
    <%= link_to 'SIGN UP', new_user_registration_path, class: "button mb-2"%>
  </div>
</div>